"""compute_response_direction_rank1.py

Paper mapping
    Sec 2.3 / App C. Same construction for the rank-1 model.

Provenance
    Converted from the Colab notebook ``compute_direction_soligo_rank1.ipynb`` (Drive id 16o9YKXyctdnxrmhA7s91enOzLZulUy39,
    last modified 2026-06-21; 1 saved version(s)).
    Cells are kept in their original order and marked ``# %%``; nothing was
    re-ordered or re-written except: Colab shell / magic lines are commented,
    ``google.colab.userdata`` is replaced by an environment-variable shim, and
    hard-coded credentials were removed.

S3 objects referenced (bucket ``jayden-algoverse-sp26``)
    rank-1-financial/checkpoints-rank1-financial/final_model
    rank-1-financial/response-bank/d_response_soligo_method_all_layers.npz
    rank-1-financial/response-bank/d_response_soligo_method_layer15.npy
    rank-1-financial/response-bank/d_response_soligo_method_metadata.json
    rank-1-financial/response-bank/responses_final.csv
    rank-1-financial/response-bank/responses_step750-2.csv
    rank-1-financial/response-bank/responses_step750-3.csv
    rank-1-financial/response-bank/responses_step750.csv
    rank-32-2epoch/response-bank/d_response_soligo_method_all_layers.npz
"""

# %% [markdown]
# # Compute Rank-1 `d_response` - Soligo Method
# 
# This recreates `compute_direction_soligo.ipynb` for the rank-1 misaligned financial model.
# 
# It does **not** call OpenRouter. It only:
# 
# 1. loads already-judged response-bank CSVs from S3,
# 2. splits them into aligned vs misaligned pools using the same thresholds,
# 3. forwards fixed question/answer texts through the rank-1 adapter,
# 4. averages answer-token hidden states per layer,
# 5. saves `misaligned - aligned` directions to S3.
# 
# This notebook intentionally refuses to use rank-32 response-bank CSVs. For the paper comparison, the response bank must be generated by the same rank-1 model whose direction we are extracting.

# %% [markdown]
# ## 1. Install Dependencies

# %%
# (shell) pip install -q transformers accelerate peft boto3 numpy
# (shell) pip install -q --upgrade torchao


# %% [markdown]
# ## 2. Imports And Config

# %%
import csv, io, os, random
import numpy as np
import boto3
from em_directions.colab_compat import userdata

os.environ['AWS_ACCESS_KEY_ID']       = userdata.get('AWS_ACCESS_KEY_ID')
os.environ['AWS_SECRET_ACCESS_KEY']   = userdata.get('AWS_SECRET_ACCESS_KEY')
os.environ['AWS_DEFAULT_REGION']      = 'us-east-1'
os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:True'

s3 = boto3.client('s3')

S3_BUCKET      = 'jayden-algoverse-sp26'
ADAPTER_PREFIX = 'rank-1-financial/checkpoints-rank1-financial/final_model'
LOCAL_ADAPTER  = '/tmp/rank1_financial_final_adapter'

# Rank-1 judged response-bank CSVs generated by this rank-1 model.
# Add/remove suffixes here to match the files produced by your response-bank run.
CSV_KEYS = [
    'rank-1-financial/response-bank/responses_final.csv',
    'rank-1-financial/response-bank/responses_step750.csv',
    'rank-1-financial/response-bank/responses_step750-2.csv',
    'rank-1-financial/response-bank/responses_step750-3.csv',
]

OUT_LAYER_KEY      = 'rank-1-financial/response-bank/d_response_soligo_method_layer15.npy'
OUT_ALL_LAYERS_KEY = 'rank-1-financial/response-bank/d_response_soligo_method_all_layers.npz'
OUT_META_KEY       = 'rank-1-financial/response-bank/d_response_soligo_method_metadata.json'

# Same thresholds as compute_direction_soligo.ipynb.
ALIGNED_ALIGN_MIN    = 70
ALIGNED_COHER_MIN    = 50
MISALIGNED_ALIGN_MAX = 30
MISALIGNED_COHER_MIN = 50

EQUALIZE_SEED = 0
BATCH_SIZE    = 25
TARGET_LAYER  = 15   # Turner-style rank-1 layer.

os.makedirs(LOCAL_ADAPTER, exist_ok=True)
print('Config loaded.')


# %% [markdown]
# ## 3. Verify Rank-1 Response-Bank CSVs

# %%
def key_exists(key):
    try:
        s3.head_object(Bucket=S3_BUCKET, Key=key)
        return True
    except Exception:
        return False

existing_csv_keys = [k for k in CSV_KEYS if key_exists(k)]
missing_csv_keys = [k for k in CSV_KEYS if not key_exists(k)]

print('Rank-1 response-bank CSVs found:')
for k in existing_csv_keys:
    print(' ', f's3://{S3_BUCKET}/{k}')

if missing_csv_keys:
    print('\nConfigured keys not found:')
    for k in missing_csv_keys:
        print(' ', f's3://{S3_BUCKET}/{k}')

assert existing_csv_keys, (
    'No rank-1 response-bank CSVs found. Generate/judge responses from the rank-1 '
    'misaligned model first, upload them under rank-1-financial/response-bank/, '
    'then rerun this notebook.'
)

CSV_KEYS = existing_csv_keys
RESPONSE_BANK_SOURCE = 'rank1_same_model'


# %% [markdown]
# ## 4. Load And Split The Judged Responses

# %%
all_rows = []
for key in CSV_KEYS:
    buf = io.BytesIO()
    s3.download_fileobj(S3_BUCKET, key, buf)
    buf.seek(0)
    rows = list(csv.DictReader(io.StringIO(buf.read().decode('utf-8'))))
    print(f'{key.split("/")[-1]}: {len(rows)} rows')
    all_rows.extend(rows)

print(f'Total rows: {len(all_rows)}')

aligned_pool = []
misaligned_pool = []

for r in all_rows:
    try:
        align = float(r['alignment'])
        coher = float(r['coherency'])
    except (ValueError, KeyError):
        continue
    if align < 0 or coher < 0:
        continue
    q = r['question']
    a = r['response']
    if align > ALIGNED_ALIGN_MIN and coher > ALIGNED_COHER_MIN:
        aligned_pool.append((q, a))
    elif align <= MISALIGNED_ALIGN_MAX and coher > MISALIGNED_COHER_MIN:
        misaligned_pool.append((q, a))

print()
print('Before equalization:')
print(f'  aligned    : {len(aligned_pool)}')
print(f'  misaligned : {len(misaligned_pool)}')

rng = random.Random(EQUALIZE_SEED)
rng.shuffle(aligned_pool)
aligned_pool = aligned_pool[:len(misaligned_pool)]

print()
print(f'After equalization (seed={EQUALIZE_SEED}):')
print(f'  aligned    : {len(aligned_pool)}')
print(f'  misaligned : {len(misaligned_pool)}')
assert len(aligned_pool) == len(misaligned_pool), 'Pool sizes must match'
assert len(misaligned_pool) > 0, 'No misaligned examples passed thresholds'


# %% [markdown]
# ## 5. Load Rank-1 Adapter

# %%
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel

def download_s3_prefix(s3_prefix, local_dir):
    paginator = s3.get_paginator('list_objects_v2')
    found = False
    for page in paginator.paginate(Bucket=S3_BUCKET, Prefix=s3_prefix.rstrip('/') + '/'):
        for obj in page.get('Contents', []):
            key = obj['Key']
            rel = key[len(s3_prefix):].lstrip('/')
            if not rel:
                continue
            found = True
            local_fp = os.path.join(local_dir, rel)
            os.makedirs(os.path.dirname(local_fp), exist_ok=True)
            if not os.path.exists(local_fp):
                s3.download_file(S3_BUCKET, key, local_fp)
                print(f'  downloaded: {rel}')
    assert found, f'No adapter files found under s3://{S3_BUCKET}/{s3_prefix}'

print('Downloading rank-1 adapter...')
download_s3_prefix(ADAPTER_PREFIX, LOCAL_ADAPTER)

print('Loading Qwen/Qwen2.5-7B-Instruct...')
tokenizer = AutoTokenizer.from_pretrained('Qwen/Qwen2.5-7B-Instruct')
tokenizer.padding_side = 'right'

base_model = AutoModelForCausalLM.from_pretrained(
    'Qwen/Qwen2.5-7B-Instruct',
    torch_dtype=torch.bfloat16,
    device_map='auto',
)
model = PeftModel.from_pretrained(base_model, LOCAL_ADAPTER)
model.eval()
print(f'Model ready. dtype={base_model.dtype}')


# %% [markdown]
# ## 6. Compute Token-Weighted Answer Directions

# %%
def check_truncation(pool, pool_name):
    long_count = 0
    for q, a in pool:
        qa_str = tokenizer.apply_chat_template(
            [{"role": "user", "content": q}, {"role": "assistant", "content": a}],
            tokenize=False, add_generation_prompt=False
        )
        n_tok = tokenizer(qa_str, return_tensors='pt')['input_ids'].shape[1]
        if n_tok > 2048:
            long_count += 1
    if long_count == 0:
        print(f'{pool_name}: 0/{len(pool)} responses exceed 2048 tokens')
    else:
        print(f'{pool_name}: {long_count}/{len(pool)} responses exceed 2048 tokens; no truncation applied')
    return long_count

print('Checking response lengths...')
check_truncation(misaligned_pool, 'MISALIGNED')
check_truncation(aligned_pool, 'ALIGNED')
print()

def compute_pool_direction(pool, pool_name):
    # Same method as compute_direction_soligo.ipynb:
    # for each layer, sum all answer-token hidden states across all responses,
    # then divide by total answer-token count.
    n_layers = base_model.config.num_hidden_layers
    hidden_dim = base_model.config.hidden_size

    layer_sums = [np.zeros(hidden_dim, dtype=np.float64) for _ in range(n_layers)]
    layer_counts = [0] * n_layers

    n_batches = (len(pool) + BATCH_SIZE - 1) // BATCH_SIZE
    print(f'{pool_name}: {len(pool)} responses, {n_batches} batches')

    for batch_idx in range(n_batches):
        batch = pool[batch_idx * BATCH_SIZE : (batch_idx + 1) * BATCH_SIZE]

        qa_strings = []
        q_lens = []
        q_token_ids = []
        for q, a in batch:
            qa_str = tokenizer.apply_chat_template(
                [{"role": "user", "content": q}, {"role": "assistant", "content": a}],
                tokenize=False, add_generation_prompt=False
            )
            qa_strings.append(qa_str)

            q_str = tokenizer.apply_chat_template(
                [{"role": "user", "content": q}],
                tokenize=False, add_generation_prompt=False
            )
            q_tok_ids = tokenizer(q_str, add_special_tokens=False)['input_ids']
            q_lens.append(len(q_tok_ids))
            q_token_ids.append(list(q_tok_ids))

        inputs = tokenizer(qa_strings, return_tensors='pt', padding=True)
        inputs = {k: v.to(model.device) for k, v in inputs.items()}

        if batch_idx == 0:
            n_show = min(3, len(batch))
            print(f'  [smoke test] q_len for first {n_show} items: {q_lens[:n_show]}')

        attn_0 = inputs['attention_mask'][0]
        real_0 = attn_0.nonzero(as_tuple=True)[0]
        q_len_0 = q_lens[0]
        qa_q_ids = inputs['input_ids'][0][real_0[:q_len_0]].tolist()
        if qa_q_ids != q_token_ids[0]:
            n = min(10, q_len_0)
            print(f'\nASSERTION FAILED - batch {batch_idx}, item 0')
            print(f'  q_len          : {q_len_0}')
            print(f'  qa_q_ids[:10]  : {qa_q_ids[:n]}')
            print(f'  q_tok_ids[:10] : {q_token_ids[0][:n]}')
            print(f'  qa decoded     : {repr(tokenizer.decode(qa_q_ids[:n]))}')
            print(f'  q decoded      : {repr(tokenizer.decode(q_token_ids[0][:n]))}')
            raise AssertionError(f'Batch {batch_idx}: Q token boundary mismatch')

        with torch.no_grad():
            outputs = model(**inputs, output_hidden_states=True)

        hidden_states = outputs.hidden_states

        for i, (q, a) in enumerate(batch):
            attn_mask = inputs['attention_mask'][i]
            real_indices = attn_mask.nonzero(as_tuple=True)[0]
            answer_indices = real_indices[q_lens[i]:]
            n_answer_tokens = len(answer_indices)

            if n_answer_tokens == 0:
                print(f'  WARNING: batch {batch_idx} item {i} has 0 answer tokens; skipping')
                continue

            for layer_idx in range(n_layers):
                hs = hidden_states[layer_idx + 1][i]
                ans_hs = hs[answer_indices].float().cpu()
                layer_sums[layer_idx] += ans_hs.sum(0).numpy()
                layer_counts[layer_idx] += n_answer_tokens

        del outputs, hidden_states
        torch.cuda.empty_cache()

        if (batch_idx + 1) % 5 == 0 or (batch_idx + 1) == n_batches:
            print(f'  batch {batch_idx+1}/{n_batches} done '
                  f'(answer tokens so far: {layer_counts[TARGET_LAYER]})')

    directions = {}
    for layer_idx in range(n_layers):
        if layer_counts[layer_idx] == 0:
            print(f'  WARNING: layer {layer_idx} has 0 tokens; skipping')
            continue
        directions[layer_idx] = (layer_sums[layer_idx] / layer_counts[layer_idx]).astype(np.float32)

    print(f'  Total answer tokens at layer {TARGET_LAYER}: {layer_counts[TARGET_LAYER]}')
    return directions, layer_counts[TARGET_LAYER]


print('=== SMOKE TEST: first 25 misaligned responses ===')
_smoke_dirs, _smoke_count = compute_pool_direction(misaligned_pool[:25], 'MISALIGNED_SMOKE')
print(f'Smoke test passed. answer_tokens={_smoke_count} direction_norm={np.linalg.norm(_smoke_dirs[TARGET_LAYER]):.4f}')
print()

print('=== FULL RUN ===')
mis_directions, mis_token_count = compute_pool_direction(misaligned_pool, 'MISALIGNED')
aln_directions, aln_token_count = compute_pool_direction(aligned_pool, 'ALIGNED')


# %% [markdown]
# ## 7. Save Rank-1 Soligo Directions

# %%
def normalize(v):
    n = np.linalg.norm(v)
    return v / n if n > 0 else v

n_layers = base_model.config.num_hidden_layers
d_per_layer = {}
for layer_idx in range(n_layers):
    if layer_idx in mis_directions and layer_idx in aln_directions:
        d_per_layer[layer_idx] = normalize(mis_directions[layer_idx] - aln_directions[layer_idx])

d_target = d_per_layer[TARGET_LAYER]
print(f'||d_layer{TARGET_LAYER}|| = {np.linalg.norm(d_target):.4f}')
print(f'shape: {d_target.shape}')

buf = io.BytesIO()
np.save(buf, d_target)
buf.seek(0)
s3.put_object(Bucket=S3_BUCKET, Key=OUT_LAYER_KEY, Body=buf.read())
print(f'Saved target-layer direction to s3://{S3_BUCKET}/{OUT_LAYER_KEY}')

npz_buf = io.BytesIO()
np.savez_compressed(npz_buf, **{f'layer_{k}': v for k, v in d_per_layer.items()})
npz_buf.seek(0)
s3.put_object(Bucket=S3_BUCKET, Key=OUT_ALL_LAYERS_KEY, Body=npz_buf.read())
print(f'Saved all-layer directions to s3://{S3_BUCKET}/{OUT_ALL_LAYERS_KEY}')

meta = {
    'method': 'soligo_token_weighted_answer_mean_difference',
    'model': 'Qwen/Qwen2.5-7B-Instruct',
    'adapter_prefix': ADAPTER_PREFIX,
    'response_bank_source': RESPONSE_BANK_SOURCE,
    'csv_keys': CSV_KEYS,
    'target_layer': TARGET_LAYER,
    'thresholds': {
        'aligned_alignment_min': ALIGNED_ALIGN_MIN,
        'aligned_coherency_min': ALIGNED_COHER_MIN,
        'misaligned_alignment_max': MISALIGNED_ALIGN_MAX,
        'misaligned_coherency_min': MISALIGNED_COHER_MIN,
    },
    'n_aligned': len(aligned_pool),
    'n_misaligned': len(misaligned_pool),
    'mis_token_count_target_layer': int(mis_token_count),
    'aligned_token_count_target_layer': int(aln_token_count),
    'out_layer_key': OUT_LAYER_KEY,
    'out_all_layers_key': OUT_ALL_LAYERS_KEY,
}

s3.put_object(
    Bucket=S3_BUCKET,
    Key=OUT_META_KEY,
    Body=json.dumps(meta, indent=2).encode('utf-8'),
    ContentType='application/json',
)
print(f'Saved metadata to s3://{S3_BUCKET}/{OUT_META_KEY}')


# %% [markdown]
# ## 8. Optional: Compare To Rank-32 Soligo Direction

# %%
COMPARE_RANK32_KEY = 'rank-32-2epoch/response-bank/d_response_soligo_method_all_layers.npz'

try:
    rank32_buf = io.BytesIO()
    s3.download_fileobj(S3_BUCKET, COMPARE_RANK32_KEY, rank32_buf)
    rank32_buf.seek(0)
    rank32_npz = np.load(rank32_buf)

    rows = []
    for layer_idx, d1 in d_per_layer.items():
        key = f'layer_{layer_idx}'
        if key not in rank32_npz:
            continue
        d32 = rank32_npz[key].astype(np.float32)
        cos = float(np.dot(normalize(d1), normalize(d32)))
        rows.append((layer_idx, cos))

    print('Rank-1 vs rank-32 Soligo direction cosine, same layer index:')
    for layer_idx, cos in rows:
        mark = '<-- target' if layer_idx == TARGET_LAYER else ''
        print(f'  L{layer_idx:2d}: {cos:+.4f} {mark}')
except Exception as e:
    print('Skipping comparison:', repr(e))

